with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  # Inventory
  github.com/Alexey-step/rocket-factory/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Alexey-step/rocket-factory/inventory/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/Alexey-step/rocket-factory/inventory/internal/config:
    config:
      include-regex: ".*Config"


  # Payment
  github.com/Alexey-step/rocket-factory/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Alexey-step/rocket-factory/payment/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/Alexey-step/rocket-factory/payment/internal/config:
    config:
      include-regex: ".*Config"


  # Order
  github.com/Alexey-step/rocket-factory/order/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Alexey-step/rocket-factory/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/Alexey-step/rocket-factory/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  github.com/Alexey-step/rocket-factory/order/internal/config:
    config:
      include-regex: ".*Config"


  # Assembly
  github.com/Alexey-step/rocket-factory/assembly/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Alexey-step/rocket-factory/assembly/internal/config:
    config:
      include-regex: ".*Config"


  # Notofication
  github.com/Alexey-step/rocket-factory/notification/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Alexey-step/rocket-factory/notification/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Alexey-step/rocket-factory/notification/internal/client/http:
    config:
      include-regex: ".*Client"


  # IAM
  github.com/Alexey-step/rocket-factory/iam/internal/service:
    config:
      include-regex: ".*Service"

  github.com/Alexey-step/rocket-factory/iam/internal/config:
    config:
      include-regex: ".*Config"

  github.com/Alexey-step/rocket-factory/iam/internal/repository:
    config:
      include-regex: ".*Repository"
