{
 "title": "Assembly Service Overview",
 "description": "Основные метрики Assembly gRPC сервиса",
 "tags": [
  "assembly",
  "grpc",
  "microservice"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Assembly duration Rate 50th percentile",
   "type": "timeseries",
   "description": "Гистограмма длительности сборки коробля",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(assembly_duration_seconds_bucket[1m]))",
     "legendFormat": "Rocket assembly duration"
    }
   ]
  },
  {
   "title": "Assembly duration Rate 95th percentile",
   "type": "timeseries",
   "description": "Гистограмма длительности сборки коробля",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(assembly_duration_seconds_bucket[1m]))",
     "legendFormat": "Rocket assembly duration"
    }
   ]
  },
  {
   "title": "Average Assembly Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(assembly_duration_seconds_sum[1m]) / rate(assembly_duration_seconds_count[1m])",
     "legendFormat": "Average duration"
    }
   ]
  }
 ]
}