{
 "title": "Order Service Overview",
 "description": "Основные метрики Order http сервиса",
 "tags": [
  "order",
  "http",
  "microservice"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Orders Count",
   "type": "timeseries",
   "description": "Количество созданных заказов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "orders_total", "legendFormat": "{{method}} - {{status}}" }
   ]
  },
  {
   "title": "Total Orders Revenue",
   "type": "timeseries",
   "description": "Суммарная выручка по заказам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    { "expr": "orders_revenue_total", "legendFormat": "{{method}} - {{status}}" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Количество запросов в секунду к Order сервису",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(order_requests_total[1m])", "legendFormat": "{{method}} - {{status}}" }
   ]
  },
  {
   "title": "Request Duration p95",
   "type": "timeseries",
   "description": "95-й перцентиль времени выполнения запросов",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(order_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "{{method}} - p95"
    }
   ]
  }
 ]
}